spring:
  config:
    activate:
      on-profile: local
    import:
      - classpath:shout-link-config/application-local.yml

---

spring:
  config:
    activate:
      on-profile: prod
    import:
      - classpath:shout-link-config/application-prod.yml
