= API 문서
:doctype: book
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:

== 인증

=== 로그인

==== request

operation::auth-controller-test/login[snippets='http-request,request-fields']

==== response

operation::auth-controller-test/login[snippets='http-response,response-fields']

== 회원

=== 회원 가입

==== request

operation::auth-controller-test/create-member[snippets='http-request,request-fields']

==== response

operation::auth-controller-test/create-member[snippets='http-response,response-fields']

== 링크 묶음

=== 링크 묶음 생성

==== request

operation::link-bundle-controller-test/create-link-bundle[snippets='http-request,request-headers,request-fields']

==== response

operation::link-bundle-controller-test/create-link-bundle[snippets='http-response,response-fields']

=== 링크 묶음 목록 조회

==== request

operation::link-bundle-controller-test/find-link-bundles[snippets='http-request,request-headers']

==== response

operation::link-bundle-controller-test/find-link-bundles[snippets='http-response,response-fields']

=== 허브 링크 묶음 생성

==== request

operation::link-bundle-controller-test/create-hub-link-bundle[snippets='http-request,request-headers,path-parameters,request-fields']

==== response

operation::link-bundle-controller-test/create-hub-link-bundle[snippets='http-response,response-fields']

=== 허브 링크 묶음 목록 조회

==== request

operation::link-bundle-controller-test/find-hub-link-bundles[snippets='http-request,request-headers,path-parameters']

==== response

operation::link-bundle-controller-test/find-hub-link-bundles[snippets='http-response,response-fields']

== 링크

=== 링크 생성

==== request

operation::link-controller-test/create-link[snippets='http-request,request-headers,request-fields']

==== response

operation::link-controller-test/create-link[snippets='http-response,response-fields']

=== 링크 목록 조회

==== request

operation::link-controller-test/find-links[snippets='http-request,request-headers,query-parameters']

=== 허브 링크 생성

==== request

operation::link-controller-test/create-hub-link[snippets='http-request,request-headers,path-parameters,request-fields']

==== response

operation::link-controller-test/create-hub-link[snippets='http-response,response-fields']

=== 허브 링크 목록 조회

==== request

operation::link-controller-test/find-hub-links[snippets='http-request,request-headers,path-parameters,query-parameters']

==== response

operation::link-controller-test/find-hub-links[snippets='http-response,response-fields']

== 허브

=== 허브 생성

==== request

operation::hub-controller-test/create-hub[snippets='http-request,request-headers,request-fields']

==== response

operation::hub-controller-test/create-hub[snippets='http-response,response-fields']

=== 허브 목록 조회

==== request

operation::hub-controller-test/find-hubs[snippets='http-request,path-parameters']

==== response

operation::hub-controller-test/find-hubs[snippets='http-response,response-fields']
