version: '3'

services:

  nginx:
    image: nginx
    ports:
      - "80:80"
    networks:
      - shoutlink
    environment:
      TZ: "Asia/Seoul"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d

  shoutlink:
    image: hseong3243/shoutlink
    ports:
      - "8080:8080"
    networks:
      - shoutlink
    environment:
      TZ: "Asia/Seoul"
    volumes:
      - ./data/logs:/logs

networks:
  shoutlink: