version: '3'

services:

  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - shoutlink
    environment:
      TZ: "Asia/Seoul"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/nginx/logs:/etc/nginx/logs
      - /home/ubuntu/data/ssl/etc/letsencrypt:/etc/letsencrypt

  shoutlink:
    image: hseong3243/shoutlink
    ports:
      - "8080:8080"
    networks:
      - shoutlink
    environment:
      TZ: "Asia/Seoul"
    volumes:
      - ./data/logs:/logs

networks:
  shoutlink:
